[package]
name = "antelope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytemuck = "1.14.0"
chrono = { version = "0.4.31", features = ["serde"] }
flate2 = "1.0.28"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0"
color-eyre = "0.6"
strum = { version = "0.25.0", features = ["derive"] }
