[package]
name = "antelope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytemuck = "1.14.0"
chrono = { version = "0.4.31", features = ["serde"] }
flate2 = "1.0.28"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["preserve_order"] }
thiserror = "1.0"
color-eyre = "0.6"
strum = { version = "0.25.0", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.1"
lazy_static = "1.4.0"
ripemd = "0.1.3"
bs58 = "0.5.0"
