[package]
name = "antelope"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytemuck = "1"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0"
color-eyre = "0.6"
strum = { version = "0.26", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
ripemd = "0.1"
bs58 = "0.5"
sha2 = "0.10"
num = "0.4"
hex = "0.4"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
