[package]
name = "antelope-abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antelope-core = { path="../antelope-core" }
bytemuck = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
color-eyre = "0.6"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
