# SPDX-FileCopyrightText: 2026 DigiGaia SCCL
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "kudu-py"
description  = "Python library for interacting with Antelope blockchains"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
rust-version = { workspace = true }
authors      = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "kudu"
crate-type = ["cdylib"]

[dependencies]
chrono             = { workspace = true }
kudu = { path = "../kudu", version = "0.2.1" }
pyo3 = { version = "0.29.0", features = ["multiple-pymethods", "chrono"] }
pythonize = "0.29.0"
serde = { version = "1.0.200", features = ["derive"] }
crabtime = "1.1.4"
