# SPDX-FileCopyrightText: 2026 DigiGaia SCCL
# SPDX-License-Identifier: AGPL-3.0-or-later

[project]
name = "kudu-py"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = [
    "version",
    "description",
    "urls",
    "authors",
    "license",
    "keywords",
]

dependencies = [
    "duct>=1.0",
    "loguru>=0.7",
]

[build-system]
requires = ["maturin>=1.11,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "python-lsp-ruff>=2.2.2",
    "python-lsp-server>=1.12.2",
]
