[package]
name = "antelope-esr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antelope-core = { path="../antelope-core" }
antelope-abi = { path="../antelope-abi" }
serde_json = { version = "1.0", features = ["preserve_order"] }
flate2 = "1.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
thiserror = "1.0"
base64 = "0.22.0"
hex = "0.4.3"
serde = { version = "1.0.200", features = ["derive"] }
