name: tests
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call: null
permissions:
  contents: read
jobs:
  tests:
    runs-on: ${{ matrix.platform.runner }}
    timeout-minutes: 15
    uses: ./.github/workflows/tests.yml
  python-tests:
    runs-on: ${{ matrix.platform.runner }}
    timeout-minutes: 15
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
    needs: tests
    steps:
      - uses: actions/checkout@v7
      - uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026
        with:
          tool: just,uv
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6
      - name: Install kudune for running python tests
        run: just install-kudune
      - name: Install pyinfra for building Vaulta image
        run: uv tool install pyinfra
      - name: Run python tests
        run: just test-python
